### ISSUE TITLE
[BUG] Source `.exports` Prior to `.path` in `.zlogin` File

### ISSUE THREAD

**Issue by bhavik2936** [bhavik2936/dot-files#4]
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this bug has not already been reported

## Description
As many variables from `.exports` file may get called in `.path` file; `.exports` file should be sourced first to instantiate them before call.

## Expected Behavior
`.exports` file must be sourced prior to sourcing of `.path` file in L2 of [`.zlogin`](https://github.com/bhavik2936/dot-files/blob/d261247168e82e7c22db60412a2ac447d7892ed0/.zlogin#L2) file.

- [x] I will abide by the [code of conduct](https://github.com/bhavik2936/dot-files/blob/main/.github/CODE_OF_CONDUCT.md).

**Comment by kishan-aghera** [comment]
Hello. I would like to take this issue.
